#!/usr/bin/env python3
"""Write the reproducible economics sensitivity report (assumptions only).

    python scripts/economics.py [--out docs]

Writes docs/economics-sensitivity.md and docs/evidence/economics.json from
backend/app/ops/economics.py. Every input is an assumption; there are no invoices and no field
data. Override a value with --set name=value (for example --set answer_rate_per_attempt=0.5).
"""

from __future__ import annotations

import argparse
import dataclasses
import json
import sys
from pathlib import Path

repo_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(repo_root / "backend"))

from app.ops import economics as eco  # noqa: E402


def money(value: float | None) -> str:
    return "n/a" if value is None else f"{value:,.0f}"


def render(report: dict) -> str:
    a, base = report["assumptions"], report["baseline"]
    lines = [
        "# Economics and break-even sensitivity (assumptions only)",
        "",
        "> **Status:** " + report["status"],
        "> Generated by `scripts/economics.py` from `backend/app/ops/economics.py`. Every number "
        "is per 1,000 cash-outs in BDT unless stated. Nothing here is a measured result.",
        "",
        "## What this model separates",
        "",
        "1. **Cost** of running the workflow: placed call attempts (failed ones included), SMS, "
        "manual review, case review with an independent follow-up, hosting.",
        "2. **Detection**: a call can surface a customer-reported mismatch. A flagged cash gap "
        "or a closed case is **not** a saved taka and is never counted as one.",
        "3. **Benefit**: only what a separate, supported intervention returns "
        "(`intervention_success_rate`). The primary cash-out has already completed when the call "
        "is made, so prevention needs a hold or reversal that this workflow does not provide on "
        "its own. With rate 0 the net is the negative of the cost.",
        "",
        "## Assumptions used",
        "",
        "| Parameter | Value |", "|---|---|",
    ]
    lines += [f"| `{k}` | {v} |" for k, v in a.items()]
    lines += [
        "",
        "## Baseline (all calls, delivery model, detection only)",
        "",
        "| Line | BDT per 1,000 |", "|---|---:|",
    ]
    lines += [f"| {k.replace('_', ' ')} | {money(v)} |" for k, v in base["cost"].items()]
    delivery = base["delivery"]
    lines += [
        "",
        f"Expected call attempts per called cash-out {delivery['expected_attempts']:.2f}; answered "
        f"within {a['max_attempts']} attempts {delivery['answered_within_budget']:.1%}; unanswered "
        f"after every attempt {delivery['unanswered_after_budget']:.1%}. "
        f"Incidents (simulated incidence {a['incident_rate']:.2%}): "
        f"{base['benefit']['incidents']}, reached by a call "
        f"{base['benefit']['incidents_reached_by_call']}. "
        f"**Net with no separate intervention: {money(base['net'])}.**",
        "",
        "## The first report's scenarios, reproduced and then corrected",
        "",
        "The report's scenarios A/B/C assume that every called incident is detected and **50% are "
        "prevented**. Re-derived with the same arithmetic:",
        "",
        "| Scenario | Cost | Benefit | Net |", "|---|---:|---:|---:|",
    ]
    for name, row in report["first_report_scenarios_reproduced"].items():
        lines.append(f"| {name} | {money(row['cost'])} | {money(row['benefit'])} | "
                     f"{money(row['net'])} |")
    lines += [
        "",
        "Same scenarios with the delivery model above and an explicit intervention rate "
        "(net per 1,000):",
        "",
        "| Scenario | Cost | 0% (detection only) | 10% | 25% | 50% | 50% + dispute savings |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for name, row in report["same_scenarios_corrected_delivery_and_explicit_intervention"].items():
        lines.append(
            f"| {name} | {money(row['cost_per_1000'])} | {money(row['intervention_0pct'])} | "
            f"{money(row['intervention_10pct'])} | {money(row['intervention_25pct'])} | "
            f"{money(row['intervention_50pct'])} | "
            f"{money(row['intervention_50pct_with_dispute_savings'])} |")
    lines += [
        "",
        "Why it differs from the report: the report's ৳2.20 per confirmation omitted failed call "
        "attempts and the human work on suspicious cases (review plus an independent follow-up). "
        "Both are modelled here and both are configurable.",
        "",
        "## Break-even",
        "",
    ]
    be = report["break_even_loss_per_incident_at_intervention_rate"]
    lines += [f"- Intervention returns {k}: break-even average loss per incident ≈ "
              f"৳{money(v)}" for k, v in be.items()]
    share = report["break_even_intervention_success"]
    lines += [
        f"- At the simulated loss of ৳{a['loss_per_incident']:.0f} per incident the intervention "
        "share needed to break even is "
        + ("above 100%: no intervention rate pays for an all-call workflow." if share is None
           else f"{share:.0%}."),
        "",
        "## Sensitivity (net per 1,000; answer rate x intervention success x loss per incident)",
        "",
        "| Answer rate | Intervention | Loss 61 | Loss 150 | Loss 300 |",
        "|---:|---:|---:|---:|---:|",
    ]
    grid: dict[tuple, dict] = {}
    for row in report["sensitivity"]:
        grid.setdefault((row["answer_rate_per_attempt"], row["intervention_success_rate"]), {})[
            row["loss_per_incident"]] = row["net"]
    for (answer, rate), losses in grid.items():
        lines.append(f"| {answer:.0%} | {rate:.0%} | {money(losses[61.0])} | "
                     f"{money(losses[150.0])} | {money(losses[300.0])} |")
    lines += [
        "",
        "Reading the table: at a lower answer rate the net can look *less* negative (for example "
        "40% versus 60% at 0% intervention) only because fewer answered calls create fewer cases "
        "and follow-ups to staff. That is cost avoided by not reaching customers, not a benefit.",
        "",
        "## Not counted anywhere",
        "",
        *[f"- {item}" for item in report["not_counted"]],
        "",
        "## What would replace these assumptions",
        "",
        "Real invoices (call and SMS price per attempt, billed unanswered fraction), measured "
        "answer and completion rates, measured manual handling time, confirmed-finding and "
        "restitution counts from a governed pilot, and a defined intervention with its own "
        "success rate. See `docs/pilot-partner-request.md`.",
    ]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default=str(repo_root / "docs"))
    parser.add_argument("--set", action="append", default=[], metavar="NAME=VALUE")
    args = parser.parse_args(argv)
    fields = {f.name: f for f in dataclasses.fields(eco.Assumptions)}
    overrides = {}
    for item in args.set:
        name, _, raw = item.partition("=")
        if name not in fields:
            parser.error(f"unknown assumption {name!r}; choose from {sorted(fields)}")
        overrides[name] = (raw.lower() == "true") if fields[name].type == "bool" else (
            int(raw) if fields[name].type == "int" else float(raw))
    report = eco.full_report(eco.Assumptions(**overrides))
    out = Path(args.out)
    (out / "evidence").mkdir(parents=True, exist_ok=True)
    (out / "economics-sensitivity.md").write_text(render(report), encoding="utf-8")
    (out / "evidence" / "economics.json").write_text(
        json.dumps(report, indent=2, sort_keys=True), encoding="utf-8")
    print(f"wrote {out / 'economics-sensitivity.md'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
